services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rocketseat-db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=root
    networks:
      - primeira-network
    volumes:
      - db:/var/lib/mysql

  api:
    container_name: api
    build:
      context: .
    ports:
      - 3001:3000
    depends_on:
      - mysql
    networks:
      - primeira-network

networks:
  primeira-network:
    driver: bridge

volumes:
  db:
    
